{{- if not .Values.signserver.useH2Database }}
{{- if .Values.database.localDeployment.deployDatabase }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
  labels:
    {{- include "signserver-ce-helm-meetup.database.labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      protocol: TCP
      targetPort: {{ .Values.database.port }}
  selector:
    {{- include "signserver-ce-helm-meetup.database.selectorLabels" . | nindent 4 }}
  type: "ClusterIP"
{{- end }}
{{- end }}