{{- if not .Values.signserver.useH2Database }}
{{- if .Values.database.localDeployment.deployDatabase }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.database.host }}
  labels:
    {{- include "signserver-ce-helm-meetup.database.labels" . | nindent 4 }}
data:
  {{- with .Values.database.localDeployment.mariadbConf }}
  custom.cnf: |+
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}