{{- if not .Values.signserver.useH2Database }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
  {{- if .Values.database.localDeployment.deployDatabase }}
  password-root: {{ .Values.database.localDeployment.passwordRoot | b64enc }}
  {{- end }}
{{- end }}